global:
  scrape_interval: 15s
  evaluation_interval: 312s

scrape_configs:
# ========= Ungrouped =========
  - job_name: mysql_exporter-copy
    static_configs:
      - targets:
          - 100.96.249.112:9104

  - job_name: public_ip_exporter
    static_configs:
      - targets:
          - 100.119.129.36:9105

# ========= Hei =========
  - job_name: company-license-expiry
    static_configs:
      - targets:
          - 172.18.0.1:9106

  - job_name: mysql_exporter
    static_configs:
      - targets:
          - 100.96.249.112:9121

